build_and_deploy:
  image: docker:stable
  stage: build
  script:
    - docker image build --no-cache --pull -t jaedle/homebridge-arm32v7:latest .
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker image push jaedle/homebridge-arm32v7:latest
  only:
    - master
